{ config, ... }:

let
  inherit (config.lib.stylix.colors) withHashtag;
in
{
  programs.vicinae = {
    enable = true;
    systemd.enable = true;
    themes.stylix = {
      meta = {
        name = "stylix";
        description = "theme generated by stylix";
        variant = "dark";
      };
      colors = {
        core = {
          background = withHashtag.base00;
          foreground = withHashtag.base05;
          secondary_background = withHashtag.base01;
          border = withHashtag.base02;
          accent = withHashtag.base0D;
        };
        accents = {
          red = withHashtag.base08;
          orange = withHashtag.base09;
          yellow = withHashtag.base0A;
          green = withHashtag.base0B;
          cyan = withHashtag.base0C;
          blue = withHashtag.base0D;
          purple = withHashtag.base0E;
          magenta = withHashtag.base0F;
        };
        list.item = {
          selection = {
            background.name = withHashtag.base02;
            secondary_background = withHashtag.base03;
          };
          hover.background = withHashtag.base01;
        };
      };
    };
  };
}
