#!/bin/sh

# Configuration
# Set background and border color
riverctl background-color 0x1e1e2e
riverctl border-color-focused 0xb4befe
riverctl border-color-unfocused 0x313244
riverctl border-color-urgent 0xf38ba8

# Set tiling configuration
riverctl attach-mode bottom
riverctl default-layout rivertile

# Set border width
riverctl border-width 1

# Set focus settings
riverctl focus-follows-cursor normal

# Hide cursor
riverctl hide-cursor timeout 2500
# riverctl hide-cursor when-typing enabled

# Enable tap
riverctl input pointer-1267-12699-ASUE120A:00_04F3:319B_Touchpad tap enabled

# Set keyboard repeat rate
riverctl set-repeat 40 300

# Make certain views start floating
riverctl float-filter-add title "Discord"
# riverctl float-filter-add title "flameshot"

# Cursor theme
riverctl xcursor-theme "Bibata-Modern-Classic" 48

#
# Keybindings
# Reload config and quit
riverctl map normal Super Q spawn '/home/soil/.config/river/init'
riverctl map normal Super+Shift Q exit

# Change focus
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Swap windows
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Change master ratio
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Change master count
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Switch outputs
riverctl map normal Super+Control J focus-output next
riverctl map normal Super+Control K focus-output previous

# Focus on urgent window (unsupported)

# Cycle between layouts (unsupported) (per tag)

# Fullscreen
riverctl map normal Super F toggle-fullscreen

# Toggle floating
riverctl map normal Super T toggle-float

# Swap master
riverctl map normal Super G zoom

# Kill
riverctl map normal Super W close

# Focus on and move windows to tags
for i in $(seq 1 5); do
	tags=$((1 << ($i - 1))) #>$#

	# Super+[1-9] to focus tag [0-8]
	riverctl map normal Super $i set-focused-tags $tags

	# Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Shift $i set-view-tags $tags
done

# Go to previous tag
riverctl map normal Super Tab focus-previous-tags

# Mouse keybindings
# Move
riverctl map-pointer normal Super BTN_LEFT move-view
# Resize
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Spawn alacritty
riverctl map normal Super Return spawn alacritty

# Spawn Menu
riverctl map normal Super Space spawn 'rofi -show drun'

# Spawn discord
riverctl map normal Super D spawn "env GDK_DPI_SCALE=2 discord"

# Spawn clipboard
riverctl map normal Super P spawn "clipman pick -t rofi"

# Lock screen (currently unsupported)
# riverctl map normal Super+Control L spawn swaylock

# Screenshot area
# riverctl map normal Super s spawn "flameshot gui -s -c -p /home/soil/stuff/pictures/screenshots"
# riverctl map normal Super S spawn "grim -g '$(slurp)' - | tee ~/stuff/pictures/\$(date +%F_%T).png | wl-copy"

# Allow certain keys in screenlocker mode
for mode in normal locked; do
	# Volume up
	riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
	riverctl map $mode Shift XF86AudioRaiseVolume spawn 'pamixer -i 1'

	# Volume down
	riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
	riverctl map $mode Shift XF86AudioLowerVolume spawn 'pamixer -d 1'

	# Mute
	riverctl map $mode None XF86AudioMute spawn 'pamixer -t'

	# Media
	riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPause spawn 'playerctl play-pause'
	riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
	riverctl map $mode None XF86AudioNext spawn 'playerctl next'

	# Backlight
	riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl set 20%+"
	riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 20%-"

	# Asus keyboard brightness
	riverctl map normal None XF86KbdBrightnessUp spawn "asusctl -n"
	riverctl map normal None XF86KbdBrightnessDown spawn "asusctl -p"
done

# Asus laptop
riverctl map normal None XF86Launch4 spawn "asusctl profile -n"
riverctl map normal None XF86Launch1 spawn "rog-control-center"

# Toggle eww
riverctl map normal Super b spawn 'eww open --toggle example'

# Passthrough mode
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# Execute rivertile
rivertile -view-padding 5 -outer-padding 5
